projects:
  Codegen Project:
    schemaPath: schema.json
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
      - src/types/amplify.ts
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/types/amplify.ts
        docsFilePath: src/graphql
        region: us-east-2
        apiId: 4dn4yqbf6jbwjasucphsiupxru
        frontend: javascript
        framework: vue
        maxDepth: 2
